version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "fix"
    open-pull-requests-limit: 1
    groups:
      dependency:
        patterns:
          - "*"