apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-certificate-tls
  namespace: default
spec:
  secretName: wildcard-certificate-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "*.history-from-the-frontier.com"
  dnsNames:
    - "*.history-from-the-frontier.com"
  usages:
    - digital signature
    - key encipherment