apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: space-exploration-ui-ingress
  annotations:
    spec.ingressClassName: gce
    kubernetes.io/ingress.allow-http: "true"
spec:
  defaultBackend:
    service:
      name: space-exploration-ui
      port:
        number: 80