apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: space-exploration-app-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
  - host: history-from-the-frontier.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ui-service
            port:
              number: 80
  - host: api-space-exploration-history-from-the-frontier.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api-space-exploration-service
            port:
              number: 8080
  - host: api-persistence-history-from-the-frontier.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api-persistence-service
            port:
              number: 8081
  tls:
  - hosts:
    - history-from-the-frontier.com
    - api-space-exploration-history-from-the-frontier.com
    - api-persistence-history-from-the-frontier.com
    secretName: nginx-tls