apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: space-exploration-app-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: address
    networking.gke.io/managed-certificates: managed-cert-ui, managed-cert-space-exploration, managed-cert-persistence
    kubernetes.io/ingress.class: gce
spec:
  rules:
  - host: history-from-the-frontier.com
    http:
      paths:
        pathType: ImplementationSpecific
        backend:
          service:
            name: ui-service
            port:
              number: 80
  - host: api-space-exploration-history-from-the-frontier.com
    http:
      paths:
        pathType: ImplementationSpecific
        backend:
          service:
            name: api-space-exploration-service
            port:
              number: 8080
  - host: api-persistence-history-from-the-frontier.com
    http:
      paths:
        pathType: ImplementationSpecific
        backend:
          service:
            name: api-persistence-service
            port:
              number: 8081