apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: space-exploration-ui-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - history-from-the-frontier.com
    secretName: space-exploration-ui-tls
  rules:
  - host: history-from-the-frontier.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: space-exploration-ui
            port:
              number: 80