apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: space-exploration-ui-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  rules:
  - host: "*.history-from-the-frontier.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: space-exploration-ui
            port:
              number: 80
  tls:
  - hosts:
    - "*.history-from-the-frontier.com"
    secretName: wildcard-certificate-tls