apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: space-exploration-ui-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: address
    networking.gke.io/managed-certificates: managed-cert-ui
    kubernetes.io/ingress.class: gce
spec:
  rules:
  - host: history-from-the-frontier.com
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: ui-service
            port:
              number: 80